---
- name: Understanding precedence of variables
  hosts: all
  gather_facts: False
  vars: 
    # USRNM: sammy
    # COMM: variable from playbook
  tasks:
    - name: create a user
      user: 
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: URSOUT

    - debug: 
        var: URSOUT

    - debug: 
        var: URSOUT