---
  - name: Copy the Apache virtual host configuration template
    template:
      src: site-config.j2  # Your template file for Apache virtual host
      dest: /etc/apache2/sites-available/your-wordpress-site.conf
      become: yes
    tags: 
      - apache

  - name: Enable the WordPress site
    apache2_module:
      state: present
      name: rewrite
      become: yes
    tags: 
      - apache

  - name: Enable the WordPress site
    apache2_site:
      name: your-wordpress-site.conf
      state: present
      become: yes
    tags: 
      - apache

  - name: Reload Apache for changes to take effect
    service:
      name: apache2
      state: reloaded
      become: yes
    tags: 
      - apache