---
- name: Setup DbServer
  hosts: dbservers
  # become: yes
  vars:
    dbname: network
    dbuser: tech
    dbpass: admin123
  tasks:
    - debug:
        var: dbname

    - debug: 
        var: dbuser

    - debug: 
        var: dbpass

    - name: Install MySQL DbServer
      yum: 
        name: mariadb-server
        state: present

    - name: install python mysql
      yum:
        name: MySQL-python
        state: present

    - name: Start and enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: "{{group}}"
        state: present
    
    - name: Create database user with name 'karo' and password 'tin@me42.' with all database privileges
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present

