---
  - name: Install Apache web server
    apt:
      name: apache2
      state: present  # Use 'latest' if you want to ensure it's up-to-date
      become: yes
    tags:
    - apache

  - name: Start and enable Apache service
    systemd:
      name: apache2
      enabled: yes
      state: started
      become: yes
    tags:
      - apache