---
- name: Setup WebServer
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache httd
      yum:
        name: httpd
        state: present
    
    - name: Start & Enable httpd
      service: 
        name: httpd
        state: started 
        enabled: yes

    - name: Copy index file
      copy: 
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        backup: yes


- name: Setup DBserver
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mysql webserver
      yum:
        name: mariadb-server
        state: present

    - name: Start & Enable mariadb service
      service:
        name: mariadb 
        state: started
        enabled: yes