---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    become: yes
  tags:
    - mysql

- name: Secure MySQL installation (set root password, etc.)
  expect:
    command: mysql_secure_installation
    responses:
    'Enter password for user root:': 'admin123'  # Set your root password here
    'Change the password for root ? ((Press y|Y for Yes, any other key for No) :': 'n'
    'Remove anonymous users? (Press y|Y for Yes, any other key for No) :': 'y'
    'Disallow root login remotely? (Press y|Y for Yes, any other key for No) :': 'y'
    'Remove test database and access to it? (Press y|Y for Yes, any other key for No) :': 'y'
    'Reload privilege tables now? (Press y|Y for Yes, any other key for No) :': 'y'
    become: yes
  tags:
    - mysql