apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticWeb
  labels:
    app: staticWeb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: staticWeb
  template:
    metadata:
      labels:
        app: staticWeb
    spec:
      containers:
      - name: staticWeb
        image: ismailmuhammed/staticweb:v1
        ports:
        - containerPort: 80